---
vault_database_name: xxxxxxyyyyyzzzzz
vault_database_user: xxxxxxyyyyyzzzzz
vault_database_password: 'xxxxxxyyyyyzzzzz'
vault_database_port: xxxxxxyyyyyzzzzz
vault_database_prefix: ''
vault_database_collation: 'utf8mb4_general_ci'

vault_server_group: xxxxxxyyyyyzzzzz
vault_project_root: xxxxxxyyyyyzzzzz
vault_keep_releases: 2
vault_backup_keep_count: 5

ansible_user: xxxxxxyyyyyzzzzz
ansible_host: xxxxxxyyyyyzzzzz
ansible_port: xxxxxxyyyyyzzzzz
vault_theme_name: xxxxxxyyyyyzzzzz
# Allowed Variables

# vault_database_name: Database name.
# vault_database_user: Database user name.
# vault_database_password: Database password. Important! The pass should be enclosed in the quotes. Something like "d$cK&5;z8"
# vault_database_port: Database port. Usually shoul be 3306.
# vault_database_prefix: Database prefix. If you dosen't use prefix for you database, you can leave this fiel empty.
# vault_database_collation: Database collation. For Drupal, this field can be "utf8mb4_general_ci" as default.
# vault_server_group: Server group in the remote server. Example: client1 (The most common value is the user accoutn name)
# vault_project_root: Project root path it is the root path of the remote server where the project is located. Example: "/home/client1/mysite.example.com"
# vault_keep_releases: Number of releases that you want to use. Example: 2
# vault_backup_keep_count: Number ot backups you want to keep
# ansible_user: SSH user name.
# ansible_host: IP address or the server domain. Example: sv5017.byethost5017.org
# ansible_port: Server port. Example: 61022
# vault_theme_name: Custom theme name - If you are using https://www.drupal.org/project/drupy the value for this variable should be "drupy" or your custom theme name.
